# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsmatch',
            name='errorrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wordsmatch',
            name='process_tag',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordsmatch',
            name='total',
            field=models.SmallIntegerField(default=0),
        ),
    ]
