# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0002_auto_20180521_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsmatch',
            name='errorrate',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='wordsmatch',
            name='total',
            field=models.TextField(default=0),
        ),
    ]
