# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-24 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M', '0004_wordsmatch_wordid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('bugs', models.TextField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
